- name: cloning rbenv
  sudo: no
  git: repo=https://github.com/sstephenson/rbenv.git
       dest=~/.rbenv

- name: cloning ruby-build
  sudo: no
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build

- name: setting zshrc
  sudo: no
  lineinfile: dest=~/.zshrc regexp="rbenv"
              insertafter=EOF
              line='export PATH="$HOME/.rbenv/bin:$PATH"; eval "$(rbenv init -)"'
